### ISSUE TITLE
Unable to find a specification for `NISdk`

### ISSUE THREAD

**Issue by ravifullestop** [network-international/payment-sdk-ios#12]
This is the below code for Podfile 
```

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'networkPaymentGateway' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'NISdk'

  # Pods for networkPaymentGateway

end
```

but getting below error while running pod install 

Analyzing dependencies

> 
[!] Unable to find a specification for `NISdk`

**Comment by mu1ex** [comment]
This could be an issue with your pod setup,

Can you try rebuilding the pod repo?
The following SO post explains it in details.

https://stackoverflow.com/a/32850706/2041906
