### ISSUE TITLE
[Critical Crash] - Direct crash after cancel processing payment 

### ISSUE THREAD

**Issue by AnasAlmomany** [network-international/payment-sdk-ios#20]
STR's 
1- present `OrderCreationViewController` with delegate and source
2- Fill Payment info 
3- Tap "Pay AED ..." While processing tap on cancel 
4- Observe the result where the app crash at `PaymentViewController` at line #152 as self is deallocated.

Console errors: 
Fatal error: Attempted to read an unowned reference but the object was already deallocated2020-02-25 17:10:30.096509+0200 MOE[72631:2682821] Fatal error: Attempted to read an unowned reference but the object was already deallocated

**Comment by mu1ex** [comment]
Hi @AnasAlmomany , thanks for the report. It will be fixed in the next release.

**Comment by AnasAlmomany** [comment]
Thanks man will be waiting for the next release 😊

**Comment by mu1ex** [comment]
Hi @AnasAlmomany , we have fixed this in v3.0.6.

**Comment by AnasAlmomany** [comment]
Thanks for the updates, Great job guys
