### ISSUE TITLE
Pay button title coming wrong

### ISSUE THREAD

**Issue by Parth-Patoliya** [network-international/payment-sdk-ios#25]
See Attachment 
Added below code in  didFinishLaunchingWithOptions
NISdk.sharedInstance.setSDKLanguage(language: "en")

![Simulator Screen Shot - iPhone 8 - 2020-03-18 at 17 55 45](https://user-images.githubusercontent.com/13760704/76960608-d248d280-6941-11ea-9c9e-e734189508d4.png)

**Comment by mu1ex** [comment]
What version of the SDK are you using @Parth-Patoliya?

**Comment by Parth-Patoliya** [comment]
3.0.5

**Comment by Parth-Patoliya** [comment]
using via cocoa-pods , just installed yesterday should be latest.

**Comment by mu1ex** [comment]
This issue was fixed it in 3.0.6, Can you try pod deintegrate and try again with version greater than 3.0.6

https://github.com/network-international/payment-sdk-ios/releases/tag/v3.0.6

**Comment by Parth-Patoliya** [comment]
Already tried but it downloads 3.0.5 version only

**Comment by Parth-Patoliya** [comment]
My code supports min os version 11.0 
Is that issue with sdk version

**Comment by mu1ex** [comment]
We do support iOS 11.
There are two things you can do - either do `pod update`
If that doesn't work try cleaning the old installation and install the new version as follows
https://stackoverflow.com/a/34765245/2041906

**Comment by Parth-Patoliya** [comment]
Okay updating pod solved issue.
