### ISSUE TITLE
ViewController does not conform to protocol 'CardPaymentDelegate'

### ISSUE THREAD

**Issue by iehsan77** [network-international/payment-sdk-ios#31]
Type 'JONetworkPaymentController' does not conform to protocol 'CardPaymentDelegate'

class JONetworkPaymentController: UIViewController  {
    
   
    override func viewDidLoad() {
        super.viewDidLoad()
        
     
        
        view.backgroundColor = .red
        
       // showCardPaymentUI(orderResponse: <#OrderResponse#>)
        
    }
    

    

}

extension JONetworkPaymentController: CardPaymentDelegate {
    func paymentDidComplete(with status: PaymentStatus) {
        print("dsadasd")
    }
    
    func authorizationDidComplete(with status: AuthorizationStatus) {
        print()
    }
    
    
}

**Comment by mu1ex** [comment]
Hi @iehsan77 , looks like you have not implemented the `CardPaymentDelegate `. Have you seen our sample app. That contains an example implementation.
