### ISSUE TITLE
invalid redeclaration of synthesized implementation for protocol requirement 'rawValue'.....  compile issue in XCode 12.5

### ISSUE THREAD

**Issue by bilalinbox06** [network-international/payment-sdk-ios#32]
Invalid redeclaration of synthesized implementation for protocol requirement 'rawValue' 

in CardPaymentDelegate & PaymentMedium files

```
public var rawValue: RawValue {
        switch self {
        case .AuthSuccess:
            return "AuthSuccess"
        case .AuthFailed:
            return "AuthFailed"
        }
    }
```

```
public var rawValue: RawValue {
        switch self {
        case .ApplePay:
            return "ApplePay"
        case .Card:
            return "Card"
        }
    }
```

**Comment by ahmermughal** [comment]
I am getting this issue too. did U find any solution for it?

**Comment by bilalinbox06** [comment]
Not yet. I am in contact with network team. Hope they will update it soon. 
Which xcode version you are using ? And it's stable version or Beta ?

**Comment by ahmermughal** [comment]
> Not yet. I am in contact with network team. Hope they will update it soon.
> Which xcode version you are using ? And it's stable version or Beta ?

Hope so too.
I am using 12.5 stable.

**Comment by mfa01** [comment]
Me too, I am using Xcode 12.5, and I got invalid redeclaration error
any help?

**Comment by bilalinbox06** [comment]
> Me too, I am using Xcode 12.5, and I got invalid redeclaration error
> any help?

use xcdoe 12.4 .... only this is is solution for now until they fix issue

**Comment by AnasAlmomany** [comment]
I created a PR , i hope they will merge it in the next release or at least create a fix here is the PR 
#33

**Comment by SkilletElveti** [comment]
Did this issue get fixed?

**Comment by AnasAlmomany** [comment]
@SkilletElveti  Its fixed on this PR but no body merged it , so weird there is no response, very bad unfortunately

**Comment by mu1ex** [comment]
Hi folks, apologies for not getting back sooner. The issue is fixed and is available in the latest release.
