### ISSUE TITLE
How to use Apple pay without using this package? 

### ISSUE THREAD

**Issue by ramisalem** [network-international/payment-sdk-ios#37]
Hello I am using react-native and i am integrating the 
Network International via react-native-ngenius package but it has an issue with Apple pay 

I went through the docs it says 

``` 
You can integrate Apple Pay with N-Genius by the following methods
1) Using the N-Genius iOS SDK
2) Direct Api Integration
 
``` 
 But i did not find any guide on how to integrate Apple Pay with Direct API Integration?

**Comment by mu1ex** [comment]
Hi, please use this link for docs around direct api integration of Apple Pay
https://docs.ngenius-payments.com/reference/apple-pay-payment-method
