### ISSUE TITLE
[SUPPORT] Compile with support for ARM64 

### ISSUE THREAD

**Issue by mahmoudajawad** [network-international/payment-sdk-ios#38]
We're unable to use this SDK on a M1 iMac as it seems it requires recompiling for ARM64 architecture.

**Comment by mu1ex** [comment]
Hi @mahmoudajawad, is there a stack trace/error log we can look into? 
How are you consuming the SDK, via Carthage or Cocoa Pods? Either case, it's a compile on fly and it should work.

**Comment by mahmoudajawad** [comment]
@mu1ex, I could produce longer stack trace, but the error is mentioned in: https://github.com/NativeScript/NativeScript/issues/9564

**Comment by mahmoudajawad** [comment]
So, cleaning up the project as well as making some calls that are wrongly documented resolved the issue for me.
