### ISSUE TITLE
Why is the browser blank after I enter the verification code

### ISSUE THREAD

**Issue by magicnana999** [network-international/payment-sdk-ios#41]
IOS sdk 4.0.2

**Comment by magicnana999** [comment]
Yes, after 10-14 ,3ds1 will not be avaliable, so I must update mobile SDK to 4.0.2

**Comment by magicnana999** [comment]
The verification HTML is Opened inside SDK. and I received the verification code. and Entered the verification code. then A blank HTML view is displayed in SDK. Bug I receive the payment success msg from my Bank

**Comment by mu1ex** [comment]
Which environment are you testing this on? Prod or Sandbox?

**Comment by magicnana999** [comment]
Prod

**Comment by magicnana999** [comment]
https://user-images.githubusercontent.com/45278519/194859652-d15ea7be-96e8-41fa-91f8-bb70c1651fc1.mp4

**Comment by magicnana999** [comment]
https://user-images.githubusercontent.com/45278519/194859757-ee6127e3-00dc-4dbf-af96-a15a74f9cd6e.mp4

**Comment by mu1ex** [comment]
this is happening for 4.0.2 version?

**Comment by magicnana999** [comment]
Is it fixed in 4.0.3 ？

**Comment by magicnana999** [comment]
@mu1ex

**Comment by mu1ex** [comment]
Can you try updating to 4.0.3.
All the issues are fixed
If you are still facing, can you provide the following

1. Environment Prod or Sandbox?
2. Order reference of the failing order
3. Status of the order under the history section in the portal

**Comment by magicnana999** [comment]
Thank you very much.
