### ISSUE TITLE
Getting issue related to the Undefined symbol in Version 4.0.2.

### ISSUE THREAD

**Issue by Vikrant2411** [network-international/payment-sdk-ios#42]
We have updated the pods of the project in one of our app and after everything setup we are getting 5 errors for which we are not getting any help. The issues are:-
**Undefined symbol: _OBJC_CLASS_$_UChallengeParameters
Undefined symbol: _OBJC_CLASS_$_UConfigParameters
Undefined symbol: _OBJC_CLASS_$_UDirectoryServer
Undefined symbol: _OBJC_CLASS_$_UThreeDS2ServiceImpl
Undefined symbol: _OBJC_CLASS_$_UUiCustomization**

Even downloaded your code and installed pods in these also and the issue is same here also.

**Can someone help to resolve this, because we have to resolve this ASAP before 14th October.** 
![Screenshot 2022-10-10 at 6 35 59 PM](https://user-images.githubusercontent.com/88380070/194873169-00b51916-53a8-4464-8af5-139d0cd4e463.png)

**Comment by mubarakansari715** [comment]
Hello @mu1ex  

I am also facing the same issue in versions 4.0.1, 4.0,2, and 4.0.3.
Kindly suggest and do needful.

**Comment by Vikrant2411** [comment]
So, are you planning for this compatibility issues for simulator?
As in device this is working.
