### ISSUE TITLE
UI related issue in Arabic Support

### ISSUE THREAD

**Issue by SachinGoswami96** [network-international/payment-sdk-ios#44]
Hello, 
       i'm using swift language for iOS native application. we are facing  UI related issue in in Arabic support. please check and let me update.

  Thanks
  Sachin Goswami
<img width="450" alt="38622fd2-555f-4660-a334-43519068b558" src="https://user-images.githubusercontent.com/84636883/196094800-12ede5c0-ed75-4343-9a55-39ce9e5d033c.png">

**Comment by mu1ex** [comment]
Have you changed the app language?

**Comment by SachinGoswami96** [comment]
Yes, I have set arabic .

**Comment by mu1ex** [comment]
@prasathr can you very and fix this?

**Comment by prasathr** [comment]
@SachinGoswami96, It is working fine with the latest version 5.0.1 Can you try out this version? Please let us know if you still face the issue after the upgrade.
