### ISSUE TITLE
Support Building for Simulator

### ISSUE THREAD

**Issue by AlaaAlHallaq** [network-international/payment-sdk-ios#45]
The new update depends on a pre-built binary framework: NI-Three-DS-Two-iOS-SDK
witch is only build for iPhone.
This disable testing the application on a simulator (to be able to test the application on multiple devices once, Screen sizes, ...).
We have 5 apps using this sdk, we need this support ASAP please.

**Comment by AlaaAlHallaq** [comment]
@mu1ex @rdhuri7 @lari-ni @nchauhan-ee

**Comment by mu1ex** [comment]
@AlaaAlHallaq , this is a shortcoming of an upstream sdk we use.
