### ISSUE TITLE
Not building app on simulator with M1 chip system

### ISSUE THREAD

**Issue by Spatel91111** [network-international/payment-sdk-ios#46]
Getting below error while build app on simulator from M1 chip system

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UChallengeParameters", referenced from:
      objc-class-ref in libNISdk.a(ThreeDSTwoViewController.o)
  "_OBJC_CLASS_$_UConfigParameters", referenced from:
      objc-class-ref in libNISdk.a(NISdk.o)
  "_OBJC_CLASS_$_UUiCustomization", referenced from:
      objc-class-ref in libNISdk.a(NISdk.o)
  "_OBJC_CLASS_$_UDirectoryServer", referenced from:
      objc-class-ref in libNISdk.a(NISdk.o)
  "_OBJC_CLASS_$_UThreeDS2ServiceImpl", referenced from:
      objc-class-ref in libNISdk.a(PaymentViewController.o)
      objc-class-ref in libNISdk.a(NISdk.o)
      objc-class-ref in libNISdk.a(ThreeDSTwoViewController.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mu1ex** [comment]
Please see this https://github.com/network-international/payment-sdk-ios/issues/48
