### ISSUE TITLE
Build Compiler issue with NISDK 4.0.4 version POD updated

### ISSUE THREAD

**Issue by mobileteamiOS** [network-international/payment-sdk-ios#48]
error build: Undefined symbol: _OBJC_CLASS_$_UThreeDS2ServiceImpl

error build: Undefined symbol: _OBJC_CLASS_$_UDirectoryServer

error build: Undefined symbol: _OBJC_CLASS_$_UUiCustomization

error build: Undefined symbol: _OBJC_CLASS_$_UChallengeParameters

error build: Undefined symbol: _OBJC_CLASS_$_UConfigParameters
![Screenshot 2022-10-19 at 11 49 59 AM](https://user-images.githubusercontent.com/50105139/196613610-cd9a9f97-98fd-4dab-91d1-d686231ca98b.png)
![ssss](https://user-images.githubusercontent.com/50105139/196615899-f978ec29-3a96-4d05-8f25-96b6890d3b9d.png)

**Comment by mu1ex** [comment]
You need to compile for device, not simulator
