### ISSUE TITLE
Build Compiler issue with NISDK 4.0.4 version POD now working in simulator

### ISSUE THREAD

**Issue by abhishekcitytech** [network-international/payment-sdk-ios#50]
Build Compiler issue with NISDK 4.0.4 version POD not working in simulator.

how can i compile in simulator in ios. without test in simulator, how can we developing application in dev mode.

error build: Undefined symbol: OBJC_CLASS$_UThreeDS2ServiceImpl

error build: Undefined symbol: OBJC_CLASS$_UDirectoryServer

error build: Undefined symbol: OBJC_CLASS$_UUiCustomization

error build: Undefined symbol: OBJC_CLASS$_UChallengeParameters

error build: Undefined symbol: OBJC_CLASS$_UConfigParameters

**Comment by mu1ex** [comment]
https://github.com/network-international/payment-sdk-ios/issues/48
