### ISSUE TITLE
Failed installing pod.

### ISSUE THREAD

**Issue by IzmYazilim** [network-international/payment-sdk-ios#51]
In the Swift language written iOS project, I try to install NISdk, but it wasn't completed successfully. 

I added pod 'NISdk' into podfile and pod install via Terminal, I got this result;

Error installing NI-Three-DS-Two-iOS-SDK
.
.
The requested URL returned error: 404

**Comment by Vikrant2411** [comment]
I am getting the same issue for this. Is there any update for this issue?

**Comment by mu1ex** [comment]
This should be fixed in the latest version of the SDK.
